name: ReportPlugin
version: '0.3-SNAPSHOT'
main: ch.framedev.reportPlugin.main.ReportPlugin
api-version: '1.21'
description: A simple Spigot plugin for reporting players. Supports SQLite, MySQL, MongoDB, and File storage.
authors:
    - Framedev

libraries:
  - org.xerial:sqlite-jdbc:3.50.3.0
  - org.mongodb:mongodb-driver-sync:5.1.0
  - com.h2database:h2:2.2.224
  - org.postgresql:postgresql:42.7.3

commands:
  report:
    description: A command to report issues or feedback.
    usage: /report <player> <message>
    permission: reportplugin.report
    permission-message: You do not have permission to report issues.
  reports-list:
    description: A command to list all reported issues.
    usage: /reportlist
    permission: reportplugin.reportlist
    permission-message: You do not have permission to view reported issues.
  report-gui:
    description: A command to open the report GUI.
    usage: /reportgui
    permission: reportplugin.reportgui
    permission-message: You do not have permission to open the report GUI.
  report-data:
    description: A command to view report data.
    usage: /reportdata
    permission: reportplugin.reportdata
    permission-message: You do not have permission to view report data.
  reporttp:
    description: A command to teleport to a reported player.
    usage: /reporttp <player> <reportID>
    permission: reportplugin.reporttp
    permission-message: You do not have permission to teleport to reported players.
  report-delete:
    description: A command to delete a report.
    usage: /report-delete <reportID>
    permission: reportplugin.reportdelete
    permission-message: You do not have permission to delete reports.
  report-updatehistory:
    description: A command to show all updates made to a report.
    usage: /report-updatehistory <reportID>
    permission: reportplugin.updatehistory
    permission-message: You do not have permission to update report history.
