name: ReportPlugin
version: '1.0-SNAPSHOT'
main: ch.framedev.reportPlugin.ReportPlugin
api-version: '1.21'
description: A simple Spigot plugin for reporting issues and feedback.
authors:
    - Framedev

commands:
  report:
    description: A command to report issues or feedback.
    usage: /report <message>
    permission: spigotTest.report
    permission-message: You do not have permission to report issues.
  reportlist:
    description: A command to list all reported issues.
    usage: /reportlist
    permission: spigotTest.reportlist
    permission-message: You do not have permission to view reported issues.
  reportgui:
    description: A command to open the report GUI.
    usage: /reportgui
    permission: spigotTest.reportgui
    permission-message: You do not have permission to open the report GUI.
