name: ReportPlugin
version: '1.0-SNAPSHOT'
main: ch.framedev.reportPlugin.main.ReportPlugin
api-version: '1.21'
description: A simple Spigot plugin for reporting issues and feedback.
authors:
    - Framedev

libraries:
  - org.xerial:sqlite-jdbc:3.50.3.0

commands:
  report:
    description: A command to report issues or feedback.
    usage: /report <player> <message>
    permission: reportplugin.report
    permission-message: You do not have permission to report issues.
  reportlist:
    description: A command to list all reported issues.
    usage: /reportlist
    permission: reportplugin.reportlist
    permission-message: You do not have permission to view reported issues.
  reportgui:
    description: A command to open the report GUI.
    usage: /reportgui
    permission: reportplugin.reportgui
    permission-message: You do not have permission to open the report GUI.
